version: "3.8"

services:
  db:
    image: postgres:15
    container_name: oficina_db
    environment:
      POSTGRES_DB: oficina
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MeuP@inscape10
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
